/*
 * Copyright 2011 Free Software Foundation, Inc.
 *
 * This file was generated by gr_modtool, a tool from the GNU Radio framework
 * This file is a part of gr-ais_simulator
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

#ifndef INCLUDED_AIS_SIMULATOR_API_H
#define INCLUDED_AIS_SIMULATOR_API_H

#include <gnuradio/attributes.h>

#ifdef gnuradio_ais_simulator_EXPORTS
#define AIS_SIMULATOR_API __GR_ATTR_EXPORT
#else
#define AIS_SIMULATOR_API __GR_ATTR_IMPORT
#endif

#endif /* INCLUDED_AIS_SIMULATOR_API_H */
