/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(websocket_pdu.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(ab3c68eddcef6fda1cac2437b1bfac11)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/ais_simulator/websocket_pdu.h>
// pydoc.h is automatically generated in the build directory
#include <websocket_pdu_pydoc.h>

void bind_websocket_pdu(py::module& m)
{

    using websocket_pdu = ::gr::ais_simulator::websocket_pdu;


    py::class_<websocket_pdu, gr::block, gr::basic_block, std::shared_ptr<websocket_pdu>>(
        m, "websocket_pdu", D(websocket_pdu))

        .def(py::init(&websocket_pdu::make),
             py::arg("addr"),
             py::arg("port"),
             D(websocket_pdu, make))


        ;
}
